trigger:
- main

pool:
  name: goofy

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: |
    dotnet restore ./HelloWorld/HelloWorld.csproj
  displayName: 'Restore dependencies'

- script: |
    dotnet build ./HelloWorld/HelloWorld.csproj --configuration Release
  displayName: 'Build Project'

- script: |
    dotnet pack ./HelloWorld/HelloWorld.csproj --configuration Release --output $(Build.ArtifactStagingDirectory)
  displayName: 'Pack NuGet Package'

- script: |
    dotnet nuget push $(Build.ArtifactStagingDirectory)/*.nupkg --source "https://pkgs.dev.azure.com/nivz267/_packaging/goofy/nuget/v3/index.json" --api-key $(System.AccessToken)
  displayName: 'Publish NuGet Package to Azure Artifacts'

- script: |
    rm -rf $(Build.ArtifactStagingDirectory)
  displayName: 'Clean Up Artifact'

- script: |
    echo "Artifact version: $(Build.BuildNumber)"
  displayName: 'Print Artifact Version'
