trigger:
- main

pool:
  name: goofy

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: |
    dotnet restore ./HelloWorld/HelloWorld.csproj
  displayName: 'Restore dependencies'

- script: |
    dotnet build ./HelloWorld/HelloWorld.csproj --configuration Release
  displayName: 'Build Project'

- script: |
    dotnet pack ./HelloWorld/HelloWorld.csproj --configuration Release --output $(Build.ArtifactStagingDirectory)
  displayName: 'Pack NuGet Package'

- task: UniversalPackages@0
  displayName: 'Publish Universal Package to Azure Artifacts'
  inputs:
    command: publish
    publishDirectory: '$(Build.ArtifactStagingDirectory)'
    vstsFeedPublish: 'hello_world/goofy'
    vstsFeedPackagePublish: 'helloworld-package'
    versionOption: patch

- script: |
    echo "Artifact Version: $(Build.BuildId)"
  displayName: 'Print Artifact Version'

- script: |
    rm -rf $(Build.ArtifactStagingDirectory)
  displayName: 'Clean Up Artifact'
